### ISSUE TITLE
MacOS 10.15.6 'Catalina' brew install fails

### ISSUE THREAD

**Issue by trcnllc** [insomniacslk/dublin-traceroute#107]
example of how to install dublin-traceroute on MAC failed with the following 

brew install https://raw.githubusercontent.com/insomniacslk/dublin-traceroute/master/homebrew/dublin-traceroute.rb
Traceback (most recent call last):
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: **Invalid usage: Non-checksummed download of dublin-traceroute formula file from an arbitrary URL is unsupported!  (UsageError)**
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: **Invalid usage: Non-checksummed download of dublin-traceroute formula file from an arbitrary URL is unsupported!  (UsageError)**

**Comment by xoengine** [comment]
I got the same error.  I did 

wget https://raw.githubusercontent.com/insomniacslk/dublin-traceroute/master/homebrew/dublin-traceroute.rb
Then did 
brew install --HEAD -s dublin-traceroute.rb

Now it bombs like this

% brew install --HEAD -s dublin-traceroute.rb
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
marp-cli
==> Updated Formulae
Updated 16 formulae.
==> Updated Casks
Updated 1 cask.

Error: Failed to load cask: dublin-traceroute.rb
Cask 'dublin-traceroute' is unreadable: wrong constant name #<Class:0x00007fb49b181198>
Warning: Treating dublin-traceroute.rb as a formula.
==> Cloning https://github.com/insomniacslk/dublin-traceroute.git
Updating /Users/mcevilly/Library/Caches/Homebrew/dublin-traceroute--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 06d4c88 [go] replace ipv6/ipv6 network library with golang.org/x/net
Entering 'googletest'
/Users/mcevilly/Library/Caches/Homebrew/dublin-traceroute--git/googletest
==> cmake .
==> make install
Last 15 lines from /Users/mcevilly/Library/Logs/Homebrew/dublin-traceroute/02.make:
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/dublintraceroute.dir/build.make CMakeFiles/dublintraceroute.dir/build
make[2]: *** No rule to make target `/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/lib/libpcap.tbd', needed by `libdublintraceroute.0.2.0.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 68%] Building CXX object CMakeFiles/dublintraceroute.dir/src/dublin_traceroute.cc.o
[ 75%] Building CXX object CMakeFiles/dublintraceroute.dir/src/hop.cc.o
[ 75%] Building CXX object CMakeFiles/dublintraceroute.dir/src/traceroute_results.cc.o
[ 75%] Building CXX object CMakeFiles/dublintraceroute.dir/src/udpv4probe.cc.o
[ 81%] Building CXX object CMakeFiles/dublintraceroute.dir/src/common.cc.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -Ddublintraceroute_EXPORTS -I/tmp/dublin-traceroute-20210520-84682-8c92a1/include -I/usr/local/Cellar/jsoncpp/1.9.4_1/include -std=c++11 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=20.4.0 -fPIC -MD -MT CMakeFiles/dublintraceroute.dir/src/traceroute_results.cc.o -MF CMakeFiles/dublintraceroute.dir/src/traceroute_results.cc.o.d -o CMakeFiles/dublintraceroute.dir/src/traceroute_results.cc.o -c /tmp/dublin-traceroute-20210520-84682-8c92a1/src/traceroute_results.cc
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -Ddublintraceroute_EXPORTS -I/tmp/dublin-traceroute-20210520-84682-8c92a1/include -I/usr/local/Cellar/jsoncpp/1.9.4_1/include -std=c++11 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=20.4.0 -fPIC -MD -MT CMakeFiles/dublintraceroute.dir/src/udpv4probe.cc.o -MF CMakeFiles/dublintraceroute.dir/src/udpv4probe.cc.o.d -o CMakeFiles/dublintraceroute.dir/src/udpv4probe.cc.o -c /tmp/dublin-traceroute-20210520-84682-8c92a1/src/udpv4probe.cc
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -Ddublintraceroute_EXPORTS -I/tmp/dublin-traceroute-20210520-84682-8c92a1/include -I/usr/local/Cellar/jsoncpp/1.9.4_1/include -std=c++11 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=20.4.0 -fPIC -MD -MT CMakeFiles/dublintraceroute.dir/src/hop.cc.o -MF CMakeFiles/dublintraceroute.dir/src/hop.cc.o.d -o CMakeFiles/dublintraceroute.dir/src/hop.cc.o -c /tmp/dublin-traceroute-20210520-84682-8c92a1/src/hop.cc
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -Ddublintraceroute_EXPORTS -I/tmp/dublin-traceroute-20210520-84682-8c92a1/include -I/usr/local/Cellar/jsoncpp/1.9.4_1/include -std=c++11 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=20.4.0 -fPIC -MD -MT CMakeFiles/dublintraceroute.dir/src/dublin_traceroute.cc.o -MF CMakeFiles/dublintraceroute.dir/src/dublin_traceroute.cc.o.d -o CMakeFiles/dublintraceroute.dir/src/dublin_traceroute.cc.o -c /tmp/dublin-traceroute-20210520-84682-8c92a1/src/dublin_traceroute.cc
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -Ddublintraceroute_EXPORTS -I/tmp/dublin-traceroute-20210520-84682-8c92a1/include -I/usr/local/Cellar/jsoncpp/1.9.4_1/include -std=c++11 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=20.4.0 -fPIC -MD -MT CMakeFiles/dublintraceroute.dir/src/common.cc.o -MF CMakeFiles/dublintraceroute.dir/src/common.cc.o.d -o CMakeFiles/dublintraceroute.dir/src/common.cc.o -c /tmp/dublin-traceroute-20210520-84682-8c92a1/src/common.cc
make[1]: *** [CMakeFiles/dublintraceroute.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	24: from /usr/local/Homebrew/Library/Homebrew/build.rb:133:in `install'
	23: from /usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:138:in `block in install'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1259:in `brew'
	20: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2318:in `stage'
	19: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:199:in `mktemp'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	12: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	11: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	10: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:110:in `chdir'
	 9: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2338:in `block in stage'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2339:in `block (2 levels) in stage'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1266:in `block in brew'
	 4: from /usr/local/Homebrew/Library/Homebrew/build.rb:178:in `block (2 levels) in install'
	 3: from /Users/mcevilly/dublin-traceroute.rb:20:in `install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2111:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2111:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2175:in `block in system': Failed executing: make install (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:494:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:440:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:444:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:66:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)

**Comment by xoengine** [comment]
Sorry for the multiple posts.  I did this and it see
cd /Library/Developer/CommandLineTools/SDKs/  
sudo ln -s MacOSX11.3.sdk MacOSX11.0.sdk 
brew install --HEAD -s dublin-traceroute.rb
It's installed.  Now to figure out how to use it.

**Comment by xoengine** [comment]
Also needed to edit to_graphviz.py to change
    print graph 
    to
    print(graph)

and 
    for flow, hops in traceroute['flows'].iteritems():<br class="Apple-interchange-newline">
to
    for flow, hops in traceroute['flows'].items():<br class="Apple-interchange-newline">

I've no clue what I'm doing but this all worked for me.
