### ISSUE TITLE
Invalid link in Python bindings for OSX

### ISSUE THREAD

**Issue by xoengine** [insomniacslk/dublin-traceroute#114]
Hi

I'm trying to get dublintrceroute re-installed.  I used it successfully a while back.  I'm following the instructions but hit this link

https://github.com/insomniacslk/dublin-traceroute/blob/master/documentation/readme/README.md#building-on-os-x.

on this page
https://github.com/insomniacslk/python-dublin-traceroute

The link is no longer valid.  Could you help with updating the correct location of the python bindings for OSX?

Thanks.

**Comment by xoengine** [comment]
Ultimately this is what I ended up with..  Any guidance would be great.

python3 ~/to_graphviz.py trace.json

Traceback (most recent call last):
  File "/Users/mcevilly/to_graphviz.py", line 124, in <module>
    main()
  File "/Users/mcevilly/to_graphviz.py", line 107, in main
    traceroute = json.load(args.jsonfile)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 596 column 60 (char 11044)
